server.port=8082
# H2 Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/prueba1
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.url=jdbc:postgresql://dpg-d2uqog6r433s73ej9g20-a.virginia-postgres.render.com:5432/agregador_d1zr
spring.datasource.username=agregador
spring.datasource.password=CAATAHDoKt464j4DenfkEc5rBXS2pk1o

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true
